Repository danieljancar/chorizo, pull requests merged in 2024-02, with the labels that each got.

#10 feat(course): initialize angular fire with appropriate documentation changes
  .gitignore
  apps/course/.firebaserc
  apps/course/angular.json
  apps/course/firebase.json
  apps/course/package-lock.json
  apps/course/package.json
  apps/course/src/app/app.component.ts
  apps/course/src/app/app.config.ts
  apps/course/src/app/features/course-detail/course-detail.component.html
  apps/course/src/app/features/courses-overview/courses-overview.component.html
  apps/course/src/app/features/courses-overview/courses-overview.component.ts
  apps/course/src/app/features/homepage/homepage.component.spec.ts
  apps/course/src/app/features/homepage/homepage.component.ts
  docs/.gitkeep
  docs/DEVELOPER-SETUP.md
Labels: documentation, enhancement, dependencies

#11 feat(course): create shared types lib for firebase data
  .gitignore
  apps/course/angular.json
  apps/course/package-lock.json
  apps/course/package.json
  apps/course/projects/types/README.md
  apps/course/projects/types/ng-package.json
  apps/course/projects/types/package.json
  apps/course/projects/types/src/lib/course.types.ts
  apps/course/projects/types/src/lib/general.types.ts
  apps/course/projects/types/src/lib/user.types.ts
  apps/course/projects/types/src/public-api.ts
  apps/course/projects/types/tsconfig.lib.json
  apps/course/projects/types/tsconfig.lib.prod.json
  apps/course/projects/types/tsconfig.spec.json
  apps/course/src/app/core/.gitkeep
  apps/course/tsconfig.json
Labels: enhancement

#13 Create a simple Navbar for the courses Tab
  README.md
  apps/course/angular.json
  apps/course/projects/types/README.md
  apps/course/projects/types/ng-package.json
  apps/course/projects/types/tsconfig.lib.json
  apps/course/projects/types/tsconfig.spec.json
  apps/course/src/app/features/homepage/homepage.component.html
  apps/course/src/app/features/homepage/homepage.component.ts
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.html
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.ts
  apps/course/src/assets/logo.png
  apps/course/tsconfig.json
Labels: enhancement

#20 18 change component library to preline
  apps/course/angular.json
  apps/course/package.json
  apps/course/src/app/features/homepage/homepage.component.html
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.html
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.ts
  apps/course/tailwind.config.js
  package-lock.json
  package.json
Labels: enhancement, UI/UX, architecture

#22 feat(course): added auth login strategy
  apps/course/angular.json
  apps/course/package-lock.json
  apps/course/package.json
  apps/course/src/app/app.component.html
  apps/course/src/app/app.component.ts
  apps/course/src/app/app.config.ts
  apps/course/src/app/app.routes.ts
  apps/course/src/app/core/auth.service.ts
  apps/course/src/app/core/toast.service.spec.ts
  apps/course/src/app/core/toast.service.ts
  apps/course/src/app/features/user/login/login.component.html
  apps/course/src/app/features/user/login/login.component.scss
  apps/course/src/app/features/user/login/login.component.spec.ts
  apps/course/src/app/features/user/login/login.component.ts
  apps/course/src/app/guards/auth.guard.spec.ts
  apps/course/src/app/guards/auth.guard.ts
  apps/course/src/app/guards/login.guard.spec.ts
  apps/course/src/app/guards/login.guard.ts
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.html
  apps/course/src/app/shared/navbar-courses-overview/navbar-courses-overview.component.ts
  apps/course/src/index.html
  apps/course/src/styles.scss
Labels: enhancement, security

#24 Create courses overview and search feature
  apps/adminui/src/App.tsx
  apps/course/projects/types/src/lib/course.types.ts
  apps/course/projects/types/src/lib/general.types.ts
  apps/course/src/app/app.component.html
  apps/course/src/app/app.component.ts
  apps/course/src/app/app.routes.ts
  apps/course/src/app/core/auth/auth.service.spec.ts
  apps/course/src/app/core/auth/auth.service.ts
  apps/course/src/app/core/data/course.service.spec.ts
  apps/course/src/app/core/data/course.service.ts
  apps/course/src/app/core/utility/toast.service.spec.ts
  apps/course/src/app/core/utility/toast.service.ts
  apps/course/src/app/enums/sort.enum.ts
  apps/course/src/app/features/auth/login/login.component.html
  apps/course/src/app/features/auth/login/login.component.scss
  apps/course/src/app/features/auth/login/login.component.spec.ts
  apps/course/src/app/features/auth/login/login.component.ts
  apps/course/src/app/features/course-detail/course-detail.component.ts
  apps/course/src/app/features/course/introduction/introduction.component.html
  apps/course/src/app/features/course/introduction/introduction.component.scss
  apps/course/src/app/features/course/introduction/introduction.component.spec.ts
  apps/course/src/app/features/course/introduction/introduction.component.ts
  apps/course/src/app/features/courses-overview/courses-overview.component.html
  apps/course/src/app/features/courses-overview/courses-overview.component.ts
  apps/course/src/app/features/home/courses/courses.component.html
  apps/course/src/app/features/home/courses/courses.component.scss
  apps/course/src/app/features/home/courses/courses.component.spec.ts
  apps/course/src/app/features/home/courses/courses.component.ts
  apps/course/src/app/features/home/courses/filter/courses-filter.component.html
  apps/course/src/app/features/home/courses/filter/courses-filter.component.scss
  apps/course/src/app/features/home/courses/filter/courses-filter.component.spec.ts
  apps/course/src/app/features/home/courses/filter/courses-filter.component.ts
  apps/course/src/app/features/home/homepage/homepage.component.html
  apps/course/src/app/features/home/homepage/homepage.component.scss
  apps/course/src/app/features/home/homepage/homepage.component.spec.ts
  apps/course/src/app/features/home/homepage/homepage.component.ts
  apps/course/src/app/guards/login.guard.ts
  apps/course/src/app/shared/loading-bars/loading-bars.component.html
  apps/course/src/app/shared/loading-bars/loading-bars.component.scss
  apps/course/src/app/shared/loading-bars/loading-bars.component.spec.ts
  apps/course/src/app/shared/loading-bars/loading-bars.component.ts
  apps/course/src/app/shared/navbar-course/navbar-course.component.html
  apps/course/src/app/shared/navbar-course/navbar-course.component.scss
  apps/course/src/app/shared/navbar-course/navbar-course.component.spec.ts
  apps/course/src/app/shared/navbar-course/navbar-course.component.ts
  apps/course/src/app/shared/navbar/navbar.component.html
  apps/course/src/app/shared/navbar/navbar.component.scss
  apps/course/src/app/shared/navbar/navbar.component.spec.ts
  apps/course/src/app/shared/navbar/navbar.component.ts
  apps/course/tsconfig.json
Labels: enhancement, UI/UX

#34 Create homepage overview
  apps/course/angular.json
  apps/course/package-lock.json
  apps/course/package.json
  apps/course/projects/types/src/lib/user.types.ts
  apps/course/src/app/app.config.ts
  apps/course/src/app/core/data/course.service.ts
  apps/course/src/app/core/data/general.service.spec.ts
  apps/course/src/app/core/data/general.service.ts
  apps/course/src/app/features/home/courses/filter/courses-filter.component.html
  apps/course/src/app/features/home/homepage/homepage.component.html
  apps/course/src/app/features/home/homepage/homepage.component.ts
  apps/course/src/app/features/home/homepage/introduction/about/homepage-about.component.html
  apps/course/src/app/features/home/homepage/introduction/about/homepage-about.component.scss
  apps/course/src/app/features/home/homepage/introduction/about/homepage-about.component.spec.ts
  apps/course/src/app/features/home/homepage/introduction/about/homepage-about.component.ts
  apps/course/src/app/features/home/homepage/introduction/markdown-renderer/homepage-markdown-renderer.component.html
  apps/course/src/app/features/home/homepage/introduction/markdown-renderer/homepage-markdown-renderer.component.scss
  apps/course/src/app/features/home/homepage/introduction/markdown-renderer/homepage-markdown-renderer.component.spec.ts
  apps/course/src/app/features/home/homepage/introduction/markdown-renderer/homepage-markdown-renderer.component.ts
  apps/course/src/app/features/home/homepage/latest-courses/latest-courses.component.html
  apps/course/src/app/features/home/homepage/latest-courses/latest-courses.component.scss
  apps/course/src/app/features/home/homepage/latest-courses/latest-courses.component.spec.ts
  apps/course/src/app/features/home/homepage/latest-courses/latest-courses.component.ts
  apps/course/src/app/features/home/homepage/subnavbar/homepage-subnavbar.component.html
  apps/course/src/app/features/home/homepage/subnavbar/homepage-subnavbar.component.scss
  apps/course/src/app/features/home/homepage/subnavbar/homepage-subnavbar.component.spec.ts
  apps/course/src/app/features/home/homepage/subnavbar/homepage-subnavbar.component.ts
  apps/course/src/app/styles/markdown.scss
  apps/course/src/app/types/general.types.ts
  apps/course/src/index.html
  apps/course/src/styles.scss
Labels: enhancement

#39 Create chorizo credits and dynamic title service
  apps/course/src/app/app.component.ts
  apps/course/src/app/features/home/courses/courses.component.ts
  apps/course/src/app/features/home/homepage/homepage.component.ts
  apps/course/src/app/shared/navigation/footer/footer.component.html
  apps/course/src/app/shared/navigation/footer/footer.component.ts
Labels: enhancement, architecture

#40 Hotfix for layout changes
  apps/course/projects/types/src/lib/course.types.ts
  apps/course/projects/types/src/public-api.ts
  apps/course/src/app/app.component.html
  apps/course/src/app/app.component.ts
  apps/course/src/app/app.routes.ts
  apps/course/src/app/core/data/course.service.ts
  apps/course/src/app/layouts/course-layout/course-layout.component.html
  apps/course/src/app/layouts/course-layout/course-layout.component.scss
  apps/course/src/app/layouts/course-layout/course-layout.component.spec.ts
  apps/course/src/app/layouts/course-layout/course-layout.component.ts
  apps/course/src/app/layouts/default-layout/default-layout.component.html
  apps/course/src/app/layouts/default-layout/default-layout.component.scss
  apps/course/src/app/layouts/default-layout/default-layout.component.spec.ts
  apps/course/src/app/layouts/default-layout/default-layout.component.ts
  apps/course/src/app/shared/navigation/navbar-course/navbar-course.component.html
  apps/course/src/app/shared/navigation/navbar-course/navbar-course.component.ts
  apps/course/src/styles.scss
Labels: architecture

#53 Create format, lint action and add commit message validator
  .commitlintrc.json
  .eslintrc.json
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/needs-review.yml
  .husky/commit-msg
  .husky/pre-commit
  apps/course/src/app/app.component.html
  apps/course/src/app/app.component.ts
  apps/course/src/app/core/auth/auth.service.ts
  apps/course/src/app/core/data/course.service.ts
  apps/course/src/app/core/utility/toast.service.ts
  apps/course/src/app/guards/auth.guard.ts
  apps/course/tsconfig.json
  package-lock.json
  package.json
Labels: enhancement, architecture

#49 Create course detail layout, navbar and introduction page
  apps/course/projects/types/src/lib/course.types.ts
  apps/course/src/app/core/data/course-state.service.spec.ts
  apps/course/src/app/core/data/course-state.service.ts
  apps/course/src/app/core/data/course.service.ts
  apps/course/src/app/core/data/image-loader.service.spec.ts
  apps/course/src/app/core/data/image-loader.service.ts
  apps/course/src/app/features/course/agenda/course-agenda.component.ts
  apps/course/src/app/features/course/documentation/course-documentation.component.ts
  apps/course/src/app/features/course/introduction/course-introduction.component.html
  apps/course/src/app/features/course/introduction/course-introduction.component.ts
  apps/course/src/app/features/course/resources/course-resources.component.ts
  apps/course/src/app/features/course/tasks/course-tasks.component.ts
  apps/course/src/app/features/home/courses/courses.component.html
  apps/course/src/app/features/home/homepage/homepage.component.html
  apps/course/src/app/features/home/homepage/markdown-renderer/homepage-markdown-renderer.component.html
  apps/course/src/app/features/home/homepage/markdown-renderer/homepage-markdown-renderer.component.ts
  apps/course/src/app/layouts/course-layout/course-layout.component.html
  apps/course/src/app/layouts/course-layout/course-layout.component.ts
  apps/course/src/app/layouts/default-layout/default-layout.component.html
  apps/course/src/app/pipes/newline-format.pipe.spec.ts
  apps/course/src/app/pipes/newline-format.pipe.ts
  apps/course/src/app/shared/navigation/navbar-course/navbar-course.component.html
  apps/course/src/app/shared/navigation/navbar-course/navbar-course.component.ts
  apps/course/src/assets/placeholder-banner.webp
Labels: enhancement, architecture, needs review

#60 Add upload banner feature with appropriate loading management
  apps/course/src/app/core/auth/auth.service.ts
  apps/course/src/app/core/data/user.service.spec.ts
  apps/course/src/app/core/data/user.service.ts
  apps/course/src/app/features/auth/account/account.component.html
  apps/course/src/app/features/auth/account/account.component.ts
  apps/course/src/app/features/auth/account/profile-banner/account-profile-banner.component.html
  apps/course/src/app/features/auth/account/profile-banner/account-profile-banner.component.ts
  apps/course/tsconfig.json
Labels: enhancement, package course
